Repository Korea-Certified-Store/backend, pull requests merged in 2024-01, with the labels that each got.

#4 feat : 스프링 프로젝트 기본 세팅 및 의존성 추가 (#3)
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/com/nainga/nainga/NaingaApplication.java
  src/main/resources/application.properties
  src/test/java/com/nainga/nainga/NaingaApplicationTests.java
Labels: ✨ Feature

#6 hotfix : PR 템플릿 일부를 수정 (#5)
  .github/pull_request_template.md
  .gitignore
Labels: 🛠️ Fix

#8 feat : MySQL 연결을 위한 프로퍼티 설정 (#7)
  src/main/resources/application-prod.yml
  src/main/resources/application.properties
  src/main/resources/application.yml
Labels: ✨ Feature

#12 [BE] Test CI 구축
  .github/workflows/action-test.yml
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/com/nainga/nainga/NaingaApplication.java
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
  src/test/java/com/nainga/nainga/NaingaApplicationTests.java
Labels: ✨ Feature

#15 Tag Entity 생성 (#10)
  src/main/java/com/nainga/nainga/domain/storetag/domain/StoreTag.java
  src/main/java/com/nainga/nainga/domain/tag/domain/Tag.java
Labels: ✨ Feature

#14 fix : 오타 수정
  .github/workflows/action-test.yml
  build.gradle
  src/test/resources/application.yml
Labels: 🛠️ Fix

#22 feat : GOOGLE API KEY 추가
  .github/workflows/action-test.yml
Labels: 🛠️ Fix

#23 feat : GOOGLE API KEY 추가
  .github/workflows/action-test.yml
Labels: 🛠️ Fix

#24 모범 음식점 가게 데이터 추가 로직 개선 (#19) feat. fix version
  .github/workflows/action-test.yml
  .gitignore
  src/main/java/com/nainga/nainga/NaingaApplication.java
  src/main/java/com/nainga/nainga/domain/store/api/StoreApi.java
  src/main/java/com/nainga/nainga/domain/store/application/GoogleMapStoreService.java
  src/main/java/com/nainga/nainga/domain/store/dao/StoreRepository.java
  src/main/java/com/nainga/nainga/domain/store/dto/CreateDividedMobeomStoresResponse.java
  src/main/java/com/nainga/nainga/domain/storecertification/dao/StoreCertificationRepository.java
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
  src/main/resources/data/mobeom/mobeom_test.xlsx
  src/test/java/com/nainga/nainga/NaingaApplicationTests.java
  src/test/java/com/nainga/nainga/domain/store/application/GoogleMapStoreServiceTest.java
  src/test/resources/application.yml
Labels: 🛠️ Fix

#29 인근 가게들의 가게 상세 정보에 Certification 추가하고 StoreCertification으로 기존 로직을 migration (#28)
  build.gradle
  src/main/java/com/nainga/nainga/domain/store/api/StoreApi.java
  src/main/java/com/nainga/nainga/domain/store/application/GoogleMapStoreService.java
  src/main/java/com/nainga/nainga/domain/store/application/StoreService.java
  src/main/java/com/nainga/nainga/domain/store/dao/StoreRepository.java
  src/main/java/com/nainga/nainga/domain/store/domain/Store.java
  src/main/java/com/nainga/nainga/domain/store/dto/StoresByLocationResponse.java
  src/main/java/com/nainga/nainga/domain/storecertification/api/StoreCertificationApi.java
  src/main/java/com/nainga/nainga/domain/storecertification/application/StoreCertificationService.java
  src/main/java/com/nainga/nainga/domain/storecertification/dao/StoreCertificationRepository.java
  src/main/java/com/nainga/nainga/domain/storecertification/dto/StoreCertificationsByLocationRequest.java
  src/main/java/com/nainga/nainga/domain/storecertification/dto/StoreCertificationsByLocationResponse.java
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
  src/test/java/com/nainga/nainga/domain/storecertification/application/StoreCertificationServiceTest.java
Labels: ✨ Feature, 📋 Docs

#34 착한가격업소 가게 데이터 추가 (#33)
  src/main/java/com/nainga/nainga/domain/store/api/StoreApi.java
  src/main/java/com/nainga/nainga/domain/store/application/GoodPriceDataParser.java
  src/main/java/com/nainga/nainga/domain/store/application/GoodPriceGoogleMapStoreService.java
  src/main/java/com/nainga/nainga/domain/store/application/GoogleMapMethods.java
  src/main/java/com/nainga/nainga/domain/store/dto/CreateDividedGoodPriceStoresResponse.java
  src/main/java/com/nainga/nainga/domain/storecertification/api/StoreCertificationApi.java
  src/main/java/com/nainga/nainga/domain/storecertification/dto/StoreCertificationsByLocationResponse.java
  src/main/resources/data/goodPrice/goodPrice_20230428.xlsx
  src/main/resources/data/goodPrice/goodPrice_test.xlsx
  src/main/resources/data/safe/safe_test.xlsx
  src/test/java/com/nainga/nainga/domain/store/application/GoodPriceDataParserTest.java
  src/test/java/com/nainga/nainga/domain/store/application/GoodPriceGoogleMapStoreServiceTest.java
  src/test/java/com/nainga/nainga/domain/store/application/SafeDataParserTest.java
Labels: ✨ Feature, ✅ Test

#36 엑셀 파일 빌드안되는것을 수정
  Dockerfile.dev
Labels: 🛠️ Fix

#38 Github Action Test CI 환경변수 수정
  .github/workflows/action-test.yml
Labels: 🛠️ Fix

#75 에러 핸들링 로직 추가 (#74)
  src/main/java/com/nainga/nainga/domain/gcsguide/GcsConfig.java
  src/main/java/com/nainga/nainga/domain/store/api/StoreApi.java
  src/main/java/com/nainga/nainga/domain/store/application/GoodPriceDataParser.java
  src/main/java/com/nainga/nainga/domain/store/application/GoogleMapMethods.java
  src/main/java/com/nainga/nainga/domain/store/application/MobeomDataParser.java
  src/main/java/com/nainga/nainga/domain/store/application/SafeDataParser.java
  src/main/java/com/nainga/nainga/global/exception/CommonErrorCode.java
  src/main/java/com/nainga/nainga/global/exception/ErrorCode.java
  src/main/java/com/nainga/nainga/global/exception/ErrorResponse.java
  src/main/java/com/nainga/nainga/global/exception/GlobalException.java
  src/main/java/com/nainga/nainga/global/exception/GlobalExceptionHandler.java
  src/main/java/com/nainga/nainga/global/exception/StoreErrorCode.java
Labels: ✨ Feature

#77 Develop to Main 릴리즈 (#76)
  src/main/java/com/nainga/nainga/domain/gcsguide/GcsConfig.java
  src/main/java/com/nainga/nainga/domain/store/api/StoreApi.java
  src/main/java/com/nainga/nainga/domain/store/application/GoodPriceDataParser.java
  src/main/java/com/nainga/nainga/domain/store/application/GoogleMapMethods.java
  src/main/java/com/nainga/nainga/domain/store/application/MobeomDataParser.java
  src/main/java/com/nainga/nainga/domain/store/application/SafeDataParser.java
  src/main/java/com/nainga/nainga/global/exception/CommonErrorCode.java
  src/main/java/com/nainga/nainga/global/exception/ErrorCode.java
  src/main/java/com/nainga/nainga/global/exception/ErrorResponse.java
  src/main/java/com/nainga/nainga/global/exception/GlobalException.java
  src/main/java/com/nainga/nainga/global/exception/GlobalExceptionHandler.java
  src/main/java/com/nainga/nainga/global/exception/StoreErrorCode.java
Labels: ✨ Feature
