Repository Korea-Certified-Store/backend, pull requests merged in 2024-02, with the labels that each got.

#83 N+1 문제 해결 및 성능 개선 (#82)
  src/main/java/com/nainga/nainga/domain/store/application/GoodPriceGoogleMapStoreService.java
  src/main/java/com/nainga/nainga/domain/store/application/MobeomGoogleMapStoreService.java
  src/main/java/com/nainga/nainga/domain/store/application/SafeGoogleMapStoreService.java
  src/main/java/com/nainga/nainga/domain/store/domain/Store.java
  src/main/java/com/nainga/nainga/domain/storecertification/dao/StoreCertificationRepository.java
  src/main/java/com/nainga/nainga/domain/storecertification/dto/StoreCertificationsByLocationResponse.java
Labels: 👷‍♂️ Refactor

#88 Develop to Main 릴리즈 (#87)
  .github/workflows/action-develop-cd.yml
  .gitignore
  build.gradle
  src/main/java/com/nainga/nainga/domain/store/application/GoodPriceGoogleMapStoreService.java
  src/main/java/com/nainga/nainga/domain/store/application/MobeomGoogleMapStoreService.java
  src/main/java/com/nainga/nainga/domain/store/application/SafeGoogleMapStoreService.java
  src/main/java/com/nainga/nainga/domain/store/domain/Store.java
  src/main/java/com/nainga/nainga/domain/storecertification/api/StoreCertificationApi.java
  src/main/java/com/nainga/nainga/domain/storecertification/application/StoreCertificationService.java
  src/main/java/com/nainga/nainga/domain/storecertification/dao/StoreCertificationRepository.java
  src/main/java/com/nainga/nainga/domain/storecertification/dto/StoreCertificationsByLocationResponse.java
  src/main/java/com/nainga/nainga/global/aspect/LogAspect.java
  src/main/resources/logback-spring.xml
  src/test/java/com/nainga/nainga/domain/storecertification/application/StoreCertificationServiceTest.java
Labels: ✨ Feature

#92 가게 검색 API 개발 (#89)
  src/main/java/com/nainga/nainga/domain/storecertification/api/StoreCertificationApi.java
  src/main/java/com/nainga/nainga/domain/storecertification/application/StoreCertificationService.java
  src/main/java/com/nainga/nainga/domain/storecertification/dao/StoreCertificationRepository.java
Labels: ✨ Feature

#104 test ci 에 Redis 추가
  .github/workflows/action-test.yml
Labels: ✨ Feature

#106 사용자 제보 API 개발 (#105)
  build.gradle
  src/main/java/com/nainga/nainga/domain/report/api/ReportApi.java
  src/main/java/com/nainga/nainga/domain/report/application/ReportService.java
  src/main/java/com/nainga/nainga/domain/report/dao/ReportRepository.java
  src/main/java/com/nainga/nainga/domain/report/domain/DelSpecificStoreReport.java
  src/main/java/com/nainga/nainga/domain/report/domain/FixSpecificStoreReport.java
  src/main/java/com/nainga/nainga/domain/report/domain/NewStoreReport.java
  src/main/java/com/nainga/nainga/domain/report/domain/Report.java
  src/main/java/com/nainga/nainga/domain/report/dto/SaveNewStoreReportRequest.java
  src/main/java/com/nainga/nainga/domain/report/dto/SaveSpecificStoreReportRequest.java
  src/main/java/com/nainga/nainga/domain/store/application/StoreService.java
  src/main/java/com/nainga/nainga/global/application/RedisSortedSetService.java
  src/main/java/com/nainga/nainga/global/exception/ReportErrorCode.java
  src/test/java/com/nainga/nainga/domain/report/application/ReportServiceTest.java
  src/test/java/com/nainga/nainga/domain/store/application/StoreServiceTest.java
Labels: ✨ Feature, ✅ Test

#114 Swagger에 API별 Exceptions 추가 (#113)
  src/main/java/com/nainga/nainga/domain/report/api/ReportApi.java
  src/main/java/com/nainga/nainga/domain/store/api/StoreApi.java
Labels: 📋 Docs

#118 일부 Swagger API Hidden 처리 (#117)
  src/main/java/com/nainga/nainga/domain/store/api/StoreApi.java
Labels: 📋 Docs

#120 Develop to Main 릴리즈 (#119)
  src/main/java/com/nainga/nainga/domain/store/api/StoreApi.java
Labels: 📋 Docs
